name       : duplicity
version    : 0.7.18.2
release    : 16
source     :
    - https://download.savannah.gnu.org/releases/duplicity/duplicity-0.7.18.2.tar.gz : c236888f43128e96cd33017b01a2855c0e24738195fed5cadad08c28fd6b6748
license    : GPL-2.0-or-later
summary    : Duplicity backs directories by producing encrypted tar-format volumes and uploading them to a remote or local file server.
component  : system.utils
description: |
    Duplicity backs directories by producing encrypted tar-format volumes and uploading them to a remote or local file server. Because duplicity uses librsync, the incremental archives are space efficient and only record the parts of files that have changed since the last backup. Because duplicity uses GnuPG to encrypt and/or sign these archives, they will be safe from spying and/or modification by the server.
builddeps  :
    - python-setuptools
    - librsync-devel
rundeps    :
    - python-fasteners
build      : |
    %python_setup
install    : |
    %python_install
