name       : duplicity
version    : 0.7.13.1
release    : 8
source     :
    - https://launchpad.net/duplicity/0.7-series/0.7.13.1/+download/duplicity-0.7.13.1.tar.gz : adb8668fb10e0b0f91cb77f758d02c02bf5c02e6c4835904a82cbdab6db4bef2
license    : GPL-2.0
summary    : Duplicity
component  : system.utils
description: |
    Duplicity backs directories by producing encrypted tar-format volumes and uploading them to a remote or local file server. Because duplicity uses librsync, the incremental archives are space efficient and only record the parts of files that have changed since the last backup. Because duplicity uses GnuPG to encrypt and/or sign these archives, they will be safe from spying and/or modification by the server.
builddeps  :
    - python-setuptools
    - librsync-devel
rundeps    :
    - python-lockfile
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
