name       : duplicity
version    : 0.8.11.1596
release    : 21
source     :
    - https://code.launchpad.net/duplicity/0.8-series/0.8.11/+download/duplicity-0.8.11.1596.tar.gz : 09826a6e5706db1fc9a2c5624fc7f13c0ec1289111676eb9b323b0c69757aae1
license    : GPL-2.0-or-later
summary    : Duplicity backs directories by producing encrypted tar-format volumes and uploading them to a remote or local file server
component  : system.utils
description: |
    Duplicity backs directories by producing encrypted tar-format volumes and uploading them to a remote or local file server. Because duplicity uses librsync, the incremental archives are space efficient and only record the parts of files that have changed since the last backup. Because duplicity uses GnuPG to encrypt and/or sign these archives, they will be safe from spying and/or modification by the server.
builddeps  :
    - pkgconfig(python3)
    - librsync-devel
rundeps    :
    - python-fasteners
    - python-future
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc
